
server:
  port: 8082

spring:
  datasource:
    drive-class-name: org.postgreSQL.Driver
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: root
    #url: jdbc:h2:file:/home/wolmir/dbh2teset
    #username: sa
    #password: 
    
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        

  h2:
    console:
      enabled: true
      path: /h2